// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.cfluturrentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqL_QIT_0MU31CjKx2cIaitgZ-ZFJqQmE',
    appId: '1:577494993263:web:5547d2b58f64121bcc809a',
    messagingSenderId: '577494993263',
    projectId: 'mentor-c8e50',
    authDomain: 'mentor-c8e50.firebaseapp.com',
    storageBucket: 'mentor-c8e50.firebasestorage.app',
    measurementId: 'G-4SNZFJCW64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAACL-ZLW0Q3qrEre008MSZok8SRndv7Fw',
    appId: '1:577494993263:android:fb471da3a9a45213cc809a',
    messagingSenderId: '577494993263',
    projectId: 'mentor-c8e50',
    storageBucket: 'mentor-c8e50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSFL1fPcZ_VsPvnv8gaxbOo4TkZV_i8kM',
    appId: '1:577494993263:ios:2c961424820bbf4ecc809a',
    messagingSenderId: '577494993263',
    projectId: 'mentor-c8e50',
    storageBucket: 'mentor-c8e50.firebasestorage.app',
    iosBundleId: 'com.example.randevu1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSFL1fPcZ_VsPvnv8gaxbOo4TkZV_i8kM',
    appId: '1:577494993263:ios:2c961424820bbf4ecc809a',
    messagingSenderId: '577494993263',
    projectId: 'mentor-c8e50',
    storageBucket: 'mentor-c8e50.firebasestorage.app',
    iosBundleId: 'com.example.randevu1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqL_QIT_0MU31CjKx2cIaitgZ-ZFJqQmE',
    appId: '1:577494993263:web:4bcc9e6f42345e16cc809a',
    messagingSenderId: '577494993263',
    projectId: 'mentor-c8e50',
    authDomain: 'mentor-c8e50.firebaseapp.com',
    storageBucket: 'mentor-c8e50.firebasestorage.app',
    measurementId: 'G-X8TDTZXYMX',
  );
}
